### ISSUE TITLE
BUG: Tipo incompatível no método of(Login login, String token) em LoginMapper.java 

### ISSUE THREAD

**Issue by FelipeSantos-cco** [Grupo-6-Projeto-Volt/BackEnd#8]
## BUG de tipo incompatível na Classe LoginMapper.java

No método `of`, desse arquivo Java, existe a reclamação referente a essa linha:
```java
 usuarioTokenDto.setUserId(login.getId());
 ```
Estourando o seguinte erro: 
```sh
java: incompatible types: java.util.UUID cannot be converted to java.lang.String
```
### Motivo do erro:
Isso acontece por conta do `UsuarioTokenDto` tem o atributo id como `String`, porém, na classe `Login` o atributo id está como `UUID`, por isso há esse problema no Mapper.

---

## Duas soluções pensadas até agora
1° Na Classe `UsuarioTokenDto` com atributo `id`, alterar de String para `UUID`, mantendo o padrão.

2° Na Classe `LoginMapper`, no método `of`, fazer a aplicação de wrap para String, da seguinte forma:
```java
usuarioTokenDto.setUserId(String.valueOf(login.getId())); // Usando o String.valueOf()
```

Essas correções resolvem o problema, porém, fiquei com algumas dúvidas sobre. 
- Qual dessas correções trás algum problema com as normas de segurança do JWT?
- Na visão de vocês, qual dessas correções podem trazer impactos grandes, como erros, bugs e problemas com o Banco de Dados?

**Comment by CaetanoDomingues** [comment]
Solução desenvolvida para a alteração do tipo da variável `id` para String
